fun_test: fun_test.cpp
	g++ -I E:\CODE\Git\Paper\cppjieba\include -o fun_test fun_test.cpp ../fun.cpp
#error_test: error_test.cpp
#	g++ -I E:\CODE\Git\Paper\cppjieba\include -o error_test error_test.cpp ../fun.cpp
.PHONY:clean
clean:
	rm -rf *.exe